### ISSUE TITLE
Playback on AUT with SWT 3.129 fails with "java.lang.NoSuchMethodError: 'org.eclipse.swt.internal.SWTEventListener"

### ISSUE THREAD

**Issue by vdulepov** [eclipse-rcptt/org.eclipse.rcptt#101]
After upgrading SWT in AUT from 3.127 to 3.129 some basic operations in tests playback ("**check**"/"**uncheck**",  "**select**" in tables, "**activate-cell-edit**") started failing with  `java.lang.NoSuchMethodError: 'org.eclipse.swt.internal.SWTEventListener org.eclipse.swt.widgets.TypedListener.getEventListener()'`.
Both in IDE and in Runner. 2.5.5 and 2.6.0 nightly.
It's still possible to record these actions though, only playback is affected.

RCPTT itself uses 3.125 (does not look related).

According to the sources of SWT 3.129, the interface is scheduled for removal in 2025-03 (so, in platform 4.35?)
```
@Deprecated(forRemoval=true, since="2025-03")
public interface SWTEventListener extends EventListener {
}
```

**Typical output:**
```
Exception happened:
java.lang.NoSuchMethodError: 'org.eclipse.swt.internal.SWTEventListener org.eclipse.swt.widgets.TypedListener.getEventListener()'
	at org.eclipse.rcptt.tesla.internal.ui.player.TeslaSWTAccess.getThis(TeslaSWTAccess.java:96)
	at org.eclipse.rcptt.tesla.internal.ui.player.TeslaSWTAccess.getTableViewer(TeslaSWTAccess.java:76)
	at org.eclipse.rcptt.tesla.internal.ui.processors.CellEditorSupport.handleActivateCellEditor(CellEditorSupport.java:158)
	at org.eclipse.rcptt.tesla.internal.ui.processors.SWTUIProcessor.executeCommand(SWTUIProcessor.java:708)
	at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.execute(AbstractTeslaClient.java:275)
	at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.doOneCommand(AbstractTeslaClient.java:247)
	at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.processNext(AbstractTeslaClient.java:129)
	at org.eclipse.rcptt.tesla.ecl.impl.TeslaBridge$2.doProcessing(TeslaBridge.java:102)
	at org.eclipse.rcptt.tesla.swt.events.TeslaEventManager.doProcessing(TeslaEventManager.java:109)
	at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$1$e269b158(DisplayAspect.aj:87)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4807)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:824)
	at org.eclipse.jface.window.Window.open_aroundBody0(Window.java:799)
	at org.eclipse.jface.window.Window.open(Window.java:785)
	at com.treeage.treeagepro.ui.dialogs.utils.preferences.TreePreferencesDialog.open(Unknown Source)
	at com.treeage.treeagepro.ui.commands.CalculationWizardHandler.execute(Unknown Source)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute_aroundBody0(HandlerProxy.java:277)
	at org.eclipse.ui.internal.handlers.HandlerProxy$AjcClosure1.run(HandlerProxy.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663bproceed(WorkbenchRecordingAspect.aj:55)
	at org.eclipse.rcptt.tesla.recording.aspects.WorkbenchRecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_WorkbenchRecordingAspect$2$943c663b(WorkbenchRecordingAspect.aj:67)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:271)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:299)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:165)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:204)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:385)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:362)
	at com.treeage.treeagepro.ui.dialogs.ModelConfigurationDialog.openWizard(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4084)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at com.treeage.treeagepro.app.Application.start(Unknown Source)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)

	at activate-cell-edit (/MyAppNameAutoTests/TP-01/00-41 Model Setup Wizard.test:39)


```

**Comment by benken-parasoft** [comment]
I noticed "type-text" isn't working in Eclipse 2025-03.  Offhand, it looks like the same issue.  I'll confirm the issue is gone once a new 2.6.0-SNAPSHOT is available.

**Comment by benken-parasoft** [comment]
I no longer see the issue in the latest 2.6.0-SNAPSHOT.  "type-text" is working again and all my tests are passing.

**Comment by vdulepov** [comment]
Good in IDE at https://ci.eclipse.org/rcptt/job/master/1983, all previously failing tests are working again.
